# NexusOps Backend Stores
from app.stores.agent_store import (
    # Legacy sync interface (in-memory)
    agent_store,
    review_store,
    installed_agents,
    clear_all,
    get_agent,
    save_agent,
    delete_agent,
    list_agents,
    register_agent,
    unregister_agent,
    is_agent_installed,
    get_install_status,
    install_agent,
    uninstall_agent,
    disable_agent,
    enable_agent,
    # New async interface (database-backed)
    async_get_agent,
    async_save_agent,
    async_delete_agent,
    async_list_agents,
    async_is_agent_installed,
    async_get_install_status,
    async_install_agent,
    async_uninstall_agent,
    async_disable_agent,
    async_enable_agent,
    async_list_installed_agents,
    async_get_agent_reviews,
    async_add_review,
    # Database models
    InstalledAgent,
    AgentReview,
    # Configuration
    set_storage_mode,
)

__all__ = [
    # Legacy sync interface
    "agent_store",
    "review_store",
    "installed_agents",
    "clear_all",
    "get_agent",
    "save_agent",
    "delete_agent",
    "list_agents",
    "register_agent",
    "unregister_agent",
    "is_agent_installed",
    "get_install_status",
    "install_agent",
    "uninstall_agent",
    "disable_agent",
    "enable_agent",
    # New async interface
    "async_get_agent",
    "async_save_agent",
    "async_delete_agent",
    "async_list_agents",
    "async_is_agent_installed",
    "async_get_install_status",
    "async_install_agent",
    "async_uninstall_agent",
    "async_disable_agent",
    "async_enable_agent",
    "async_list_installed_agents",
    "async_get_agent_reviews",
    "async_add_review",
    # Database models
    "InstalledAgent",
    "AgentReview",
    # Configuration
    "set_storage_mode",
]
